### ISSUE TITLE
Creating the Rules & Guidelines page and  profile page

### ISSUE THREAD

**Issue by Bridgetlawani** [zuri-training/Team_26_Repo-Proj_Price_Compare#13]

**Comment by alaswadiyy** [comment]
Mobile and Desktop view completed
![Screenshot (34)](https://user-images.githubusercontent.com/42524814/183878456-8c484656-ccab-4a75-8252-cf6ad3bc7df5.png)
![Screenshot (35)](https://user-images.githubusercontent.com/42524814/183879972-419b4ee0-d801-4d05-9eb1-e3c11c5bae74.png)
